// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.20;

import "forge-std/Script.sol";
import "forge-std/StdJson.sol";
import "../src/ShieldedPool.sol";
import "../src/AuditRegistry.sol";
import "../src/IVerifier.sol";
import "@openzeppelin/contracts/token/ERC20/ERC20.sol";

contract FullE2EVerifier is IVerifier {
    function verifyProof(
        uint256[2] calldata,
        uint256[2][2] calldata,
        uint256[2] calldata,
        uint256[14] calldata
    ) external pure override returns (bool) {
        return true;
    }
}

contract FullE2EToken is ERC20 {
    constructor() ERC20("Full E2E Token", "FET") {
        _mint(msg.sender, 1000 ether);
    }
}

contract TestFullE2EFlowScript is Script {
    using stdJson for string;

    function run() external {
        // Read DKG test data generated by client
        string memory rootPath = vm.projectRoot();
        string memory jsonPath = string.concat(rootPath, "/test/dkg_test_data.json");
        string memory json = vm.readFile(jsonPath);
        
        bytes memory globalPubKey = json.readBytes(".global_public_key");
        bytes memory sampleCiphertext = json.readBytes(".sample_ciphertext");

        // Set up Anvil accounts
        uint256 alicePrivateKey = 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80; // Account 0
        address alice = vm.addr(alicePrivateKey);
        address bob = address(0x111122223333444455556666777788889999aAaa);

        address[5] memory auditors = [
            json.readAddress(".nodes[0].address"),
            json.readAddress(".nodes[1].address"),
            json.readAddress(".nodes[2].address"),
            json.readAddress(".nodes[3].address"),
            json.readAddress(".nodes[4].address")
        ];

        uint256[5] memory auditorPrivateKeys = [
            0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d, // Key 1
            0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a, // Key 2
            0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6, // Key 3
            0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a, // Key 4
            0x8b3a350cf5c34c9194ca85829a2df0ec3153be0318b5e2d3348e872092edffba  // Key 5
        ];

        // START BROADCAST FOR DEPLOYMENT
        vm.startBroadcast(alicePrivateKey);

        FullE2EToken token = new FullE2EToken();
        FullE2EVerifier verifier = new FullE2EVerifier();
        
        // Deploy Poseidon
        string memory bytecodePath = string.concat(rootPath, "/../Poseidon_bytecode.txt");
        string memory bytecode = vm.readFile(bytecodePath);
        bytes memory poseidonBytecode = vm.parseBytes(bytecode);
        address poseidon2;
        assembly {
            poseidon2 := create(0, add(poseidonBytecode, 0x20), mload(poseidonBytecode))
        }
        require(poseidon2 != address(0), "Poseidon deployment failed");

        ShieldedPool pool = new ShieldedPool(
            address(token),
            address(verifier),
            poseidon2,
            alice
        );

        AuditRegistry registry = new AuditRegistry(auditors);

        console.log("=== Contracts Deployed ===");
        console.log("Token address:", address(token));
        console.log("ShieldedPool address:", address(pool));
        console.log("AuditRegistry address:", address(registry));

        vm.stopBroadcast();

        // ==========================================
        // 步骤 1: DKG 节点注册及公钥公示
        // ==========================================
        for (uint i = 0; i < 5; i++) {
            bytes memory commKey = json.readBytes(string.concat(".nodes[", vm.toString(i), "].communication_key"));
            bytes[3] memory commitments;
            commitments[0] = json.readBytes(string.concat(".nodes[", vm.toString(i), "].commitments[0]"));
            commitments[1] = json.readBytes(string.concat(".nodes[", vm.toString(i), "].commitments[1]"));
            commitments[2] = json.readBytes(string.concat(".nodes[", vm.toString(i), "].commitments[2]"));

            bytes[5] memory shares;
            for (uint j = 0; j < 5; j++) {
                shares[j] = json.readBytes(string.concat(".nodes[", vm.toString(i), "].shares[", vm.toString(j), "]"));
            }

            vm.startBroadcast(auditorPrivateKeys[i]);
            registry.registerCommunicationKey(commKey);
            registry.submitDkgData(commitments, auditors, shares);
            vm.stopBroadcast();
        }

        // Finalize Global Public Key on-chain
        vm.startBroadcast(auditorPrivateKeys[0]);
        registry.finalizeGlobalPublicKey(globalPubKey);
        vm.stopBroadcast();
        console.log("Step 1: DKG DKG completed on-chain.");

        // ==========================================
        // 步骤 2: Alice 存款 (Deposit 10 FET)
        // ==========================================
        vm.startBroadcast(alicePrivateKey);
        token.approve(address(pool), 10 ether);
        bytes32 aliceCommitment = bytes32(uint256(0x1111111111111111111111111111111111111111111111111111111111111111));
        pool.deposit(aliceCommitment, 10 ether);
        vm.stopBroadcast();
        console.log("Step 2: Alice deposited 10 FET to ShieldedPool.");

        // ==========================================
        // 步骤 3: Alice 隐私转账给 Bob (Transact)
        // ==========================================
        // Alice splits 10 FET note into:
        // - Bob's note: 5 FET (commitment2)
        // - Alice's change note: 5 FET (commitment3)
        // This transaction is private (publicAmount = 0).
        // It carries the encrypted audit data (sampleCiphertext).
        bytes memory mockProof = abi.encode(
            [uint256(0), uint256(0)],
            [[uint256(0), uint256(0)], [uint256(0), uint256(0)]],
            [uint256(0), uint256(0)]
        );
        bytes32 root = pool.getRoot();
        bytes32 nullifierAlice = bytes32(uint256(0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa));
        bytes32 commitmentBob = bytes32(uint256(0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb));
        bytes32 commitmentAliceChange = bytes32(uint256(0xcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc));
        uint256[4] memory mockAuditCiphertext = [uint256(1), uint256(2), uint256(3), uint256(4)];

        vm.startBroadcast(alicePrivateKey);
        pool.transact(
            mockProof,
            root,
            bytes32(0),
            nullifierAlice,
            bytes32(uint256(0x2222222222222222222222222222222222222222222222222222222222222222)), // unique dummy nullifier2
            commitmentBob,
            commitmentAliceChange,
            0, // publicAmount = 0 (private transfer)
            address(0),
            address(0),
            0,
            sampleCiphertext, // Encrypted audit data
            mockAuditCiphertext
        );
        vm.stopBroadcast();
        console.log("Step 3: Alice privately transferred 5 FET to Bob (carrying audit data).");

        // ==========================================
        // 步骤 4: Bob 提取 5 FET (Withdrawal)
        // ==========================================
        // Bob spends his 5 FET note, transferring it to his external Ethereum address.
        bytes32 nullifierBob = bytes32(uint256(0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb));
        
        vm.startBroadcast(alicePrivateKey); // using alice to call transaction representing Bob's withdrawal
        pool.transact(
            mockProof,
            pool.getRoot(),
            bytes32(0),
            nullifierBob,
            bytes32(uint256(0x4444444444444444444444444444444444444444444444444444444444444444)), // unique dummy nullifier2
            bytes32(0),
            bytes32(0),
            -5 ether, // publicAmount = -5 (withdrawal)
            bob, // Bob's external address
            address(0),
            0,
            "", // no audit data needed for public withdrawal
            mockAuditCiphertext
        );
        vm.stopBroadcast();
        console.log("Step 4: Bob withdrew 5 FET to external address.");
        console.log("Bob's external balance:", token.balanceOf(bob));
        console.log("ShieldedPool remaining balance:", token.balanceOf(address(pool)));
    }
}
